# Generated by Django 5.2.17 on 2026-09-08 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Edited'), ('DELETE', 'Deleted'), ('CONFIRM', 'Confirmed'), ('REJECT', 'Rejected'), ('CLOSE', 'Closed the month'), ('REOPEN', 'Reopened the month')], max_length=8)),
                ('model', models.CharField(max_length=40)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=140)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model', 'object_id'], name='core_auditl_model_cea205_idx'), models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='months_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='one_close_per_month')],
            },
        ),
    ]
