# Generated by Django 5.2.17 on 2026-09-08 18:00

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(default='#3a34c9', max_length=7)),
                ('is_recurring_by_default', models.BooleanField(default=False)),
                ('prorate_by_tenancy', models.BooleanField(default=False, help_text='Charge only for the days someone was living here.', verbose_name='Prorate by move-in / move-out')),
                ('prorate_by_presence', models.BooleanField(default=False, help_text='Also discount the days someone was away. Use for food, gas, maid.', verbose_name='Prorate by away days')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for a variable bill nobody knows the total of yet.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(default=datetime.date.today)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equally'), ('EXACT', 'Exact amounts'), ('PERCENT', 'Percentages'), ('SHARES', 'Shares')], default='EQUAL', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='expenses.expense')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('share_units', models.PositiveIntegerField(blank=True, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('present_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='expenses_ex_date_2850f8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_deleted', 'is_draft'], name='expenses_ex_is_dele_2c6079_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseshare',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='one_share_per_person_per_expense'),
        ),
    ]
