# Generated by Django 5.2.17 on 2026-09-08 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_seed_categories'),
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='recurring.recurringexpense'),
        ),
    ]
