# Generated by Django 5.2.17 on 2026-09-08 18:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for a bill that changes every month.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_variable', models.BooleanField(default=False, help_text='Generate a draft with no amount, for somebody to fill in.')),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equally'), ('EXACT', 'Exact amounts'), ('PERCENT', 'Percentages'), ('SHARES', 'Shares')], default='EQUAL', max_length=10)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Every month'), ('QUARTERLY', 'Every three months'), ('YEARLY', 'Every year')], default='MONTHLY', max_length=9)),
                ('covers_whole_month', models.BooleanField(default=True, help_text='Set the expense period to the whole month, so proration works.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_templates', to='expenses.category')),
                ('default_participants', models.ManyToManyField(blank=True, help_text='Leave empty to use whoever is living here when it generates.', related_name='recurring_templates', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, help_text='Who usually pays this. Can be changed on the generated expense.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_month', 'description'],
            },
        ),
    ]
