# Generated by Django 5.2.17 on 2026-09-08 18:13

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(default=datetime.date.today)),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('BANK', 'Bank transfer')], default='UPI', max_length=6)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be confirmed'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=9)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['status', 'to_user'], name='settlements_status_fa3860_idx')],
            },
        ),
    ]
